#ifndef WORKSPACE_H
#define WORKSPACE_H

/*
 * This file was autogenerated by OSQP-Python on March 04, 2026 at 18:53:05.
 * 
 * This file contains the prototypes for all the workspace variables needed
 * by OSQP. The actual data is contained inside workspace.c.
 */

#include "types.h"
#include "qdldl_interface.h"

// Data structure prototypes
extern csc Pdata;
extern csc Adata;
extern c_float qdata[168];
extern c_float ldata[280];
extern c_float udata[280];
extern OSQPData data;

// Settings structure prototype
extern OSQPSettings settings;

// Scaling structure prototypes
extern c_float Dscaling[168];
extern c_float Dinvscaling[168];
extern c_float Escaling[280];
extern c_float Einvscaling[280];
extern OSQPScaling scaling;

// Prototypes for linsys_solver structure
extern csc linsys_solver_L;
extern c_float linsys_solver_Dinv[448];
extern c_int linsys_solver_P[448];
extern c_float linsys_solver_bp[448];
extern c_float linsys_solver_sol[448];
extern c_float linsys_solver_rho_inv_vec[280];
extern c_int linsys_solver_Pdiag_idx[168];
extern csc linsys_solver_KKT;
extern c_int linsys_solver_PtoKKT[14196];
extern c_int linsys_solver_AtoKKT[504];
extern c_int linsys_solver_rhotoKKT[280];
extern QDLDL_float linsys_solver_D[448];
extern QDLDL_int linsys_solver_etree[448];
extern QDLDL_int linsys_solver_Lnz[448];
extern QDLDL_int   linsys_solver_iwork[1344];
extern QDLDL_bool  linsys_solver_bwork[448];
extern QDLDL_float linsys_solver_fwork[448];
extern qdldl_solver linsys_solver;

// Prototypes for solution
extern c_float xsolution[168];
extern c_float ysolution[280];

extern OSQPSolution solution;

// Prototype for info structure
extern OSQPInfo info;

// Prototypes for the workspace
extern c_float work_rho_vec[280];
extern c_float work_rho_inv_vec[280];
extern c_int work_constr_type[280];
extern c_float work_x[168];
extern c_float work_y[280];
extern c_float work_z[280];
extern c_float work_xz_tilde[448];
extern c_float work_x_prev[168];
extern c_float work_z_prev[280];
extern c_float work_Ax[280];
extern c_float work_Px[168];
extern c_float work_Aty[168];
extern c_float work_delta_y[280];
extern c_float work_Atdelta_y[168];
extern c_float work_delta_x[168];
extern c_float work_Pdelta_x[168];
extern c_float work_Adelta_x[280];
extern c_float work_D_temp[168];
extern c_float work_D_temp_A[168];
extern c_float work_E_temp[280];

extern OSQPWorkspace workspace;

#endif // ifndef WORKSPACE_H
