"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class Body(object):
    __slots__ = ["position", "orientation", "orientation_quaternion", "lin_vel", "ang_vel"]

    __typenames__ = ["double", "double", "double", "double", "double"]

    __dimensions__ = [[3], [3], [4], [3], [3]]

    def __init__(self):
        self.position = [ 0.0 for dim0 in range(3) ]
        self.orientation = [ 0.0 for dim0 in range(3) ]
        self.orientation_quaternion = [ 0.0 for dim0 in range(4) ]
        self.lin_vel = [ 0.0 for dim0 in range(3) ]
        self.ang_vel = [ 0.0 for dim0 in range(3) ]

    def encode(self):
        buf = BytesIO()
        buf.write(Body._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>3d', *self.position[:3]))
        buf.write(struct.pack('>3d', *self.orientation[:3]))
        buf.write(struct.pack('>4d', *self.orientation_quaternion[:4]))
        buf.write(struct.pack('>3d', *self.lin_vel[:3]))
        buf.write(struct.pack('>3d', *self.ang_vel[:3]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != Body._get_packed_fingerprint():
            raise ValueError("Decode error")
        return Body._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = Body()
        self.position = struct.unpack('>3d', buf.read(24))
        self.orientation = struct.unpack('>3d', buf.read(24))
        self.orientation_quaternion = struct.unpack('>4d', buf.read(32))
        self.lin_vel = struct.unpack('>3d', buf.read(24))
        self.ang_vel = struct.unpack('>3d', buf.read(24))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if Body in parents: return 0
        tmphash = (0x24b6b6d20095e2f0) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if Body._packed_fingerprint is None:
            Body._packed_fingerprint = struct.pack(">Q", Body._get_hash_recursive([]))
        return Body._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", Body._get_packed_fingerprint())[0]

