/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package mors_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class BodyWBC implements lcm.lcm.LCMEncodable
{
    public double position[];
    public double orientation_euler[];
    public double orientation_quaternion[];
    public double lin_vel[];
    public double ang_vel[];
 
    public BodyWBC()
    {
        position = new double[3];
        orientation_euler = new double[3];
        orientation_quaternion = new double[4];
        lin_vel = new double[3];
        ang_vel = new double[3];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xdb2fcc3ba94fc65aL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(mors_msgs.BodyWBC.class))
            return 0L;
 
        classes.add(mors_msgs.BodyWBC.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.position[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.orientation_euler[a]); 
        }
 
        for (int a = 0; a < 4; a++) {
            outs.writeDouble(this.orientation_quaternion[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.lin_vel[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.ang_vel[a]); 
        }
 
    }
 
    public BodyWBC(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public BodyWBC(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static mors_msgs.BodyWBC _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        mors_msgs.BodyWBC o = new mors_msgs.BodyWBC();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.position = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.position[a] = ins.readDouble();
        }
 
        this.orientation_euler = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.orientation_euler[a] = ins.readDouble();
        }
 
        this.orientation_quaternion = new double[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.orientation_quaternion[a] = ins.readDouble();
        }
 
        this.lin_vel = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.lin_vel[a] = ins.readDouble();
        }
 
        this.ang_vel = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.ang_vel[a] = ins.readDouble();
        }
 
    }
 
    public mors_msgs.BodyWBC copy()
    {
        mors_msgs.BodyWBC outobj = new mors_msgs.BodyWBC();
        outobj.position = new double[(int) 3];
        System.arraycopy(this.position, 0, outobj.position, 0, 3); 
        outobj.orientation_euler = new double[(int) 3];
        System.arraycopy(this.orientation_euler, 0, outobj.orientation_euler, 0, 3); 
        outobj.orientation_quaternion = new double[(int) 4];
        System.arraycopy(this.orientation_quaternion, 0, outobj.orientation_quaternion, 0, 4); 
        outobj.lin_vel = new double[(int) 3];
        System.arraycopy(this.lin_vel, 0, outobj.lin_vel, 0, 3); 
        outobj.ang_vel = new double[(int) 3];
        System.arraycopy(this.ang_vel, 0, outobj.ang_vel, 0, 3); 
        return outobj;
    }
 
}

