/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package mors_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class contact_sensor_msg implements lcm.lcm.LCMEncodable
{
    public boolean contact_states[];
 
    public contact_sensor_msg()
    {
        contact_states = new boolean[4];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xe919c2135e4a3708L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(mors_msgs.contact_sensor_msg.class))
            return 0L;
 
        classes.add(mors_msgs.contact_sensor_msg.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        for (int a = 0; a < 4; a++) {
            outs.writeByte( this.contact_states[a] ? 1 : 0); 
        }
 
    }
 
    public contact_sensor_msg(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public contact_sensor_msg(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static mors_msgs.contact_sensor_msg _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        mors_msgs.contact_sensor_msg o = new mors_msgs.contact_sensor_msg();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.contact_states = new boolean[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.contact_states[a] = ins.readByte()!=0;
        }
 
    }
 
    public mors_msgs.contact_sensor_msg copy()
    {
        mors_msgs.contact_sensor_msg outobj = new mors_msgs.contact_sensor_msg();
        outobj.contact_states = new boolean[(int) 4];
        System.arraycopy(this.contact_states, 0, outobj.contact_states, 0, 4); 
        return outobj;
    }
 
}

