"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class contact_sensor_msg(object):
    __slots__ = ["contact_states"]

    __typenames__ = ["boolean"]

    __dimensions__ = [[4]]

    def __init__(self):
        self.contact_states = [ False for dim0 in range(4) ]

    def encode(self):
        buf = BytesIO()
        buf.write(contact_sensor_msg._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>4b', *self.contact_states[:4]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != contact_sensor_msg._get_packed_fingerprint():
            raise ValueError("Decode error")
        return contact_sensor_msg._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = contact_sensor_msg()
        self.contact_states = [bool(x) for x in struct.unpack('>4b', buf.read(4))]
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if contact_sensor_msg in parents: return 0
        tmphash = (0xe919c2135e4a3708) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if contact_sensor_msg._packed_fingerprint is None:
            contact_sensor_msg._packed_fingerprint = struct.pack(">Q", contact_sensor_msg._get_hash_recursive([]))
        return contact_sensor_msg._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", contact_sensor_msg._get_packed_fingerprint())[0]

