"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class enable_msg(object):
    __slots__ = ["locomotion_en", "locomotion_reset", "leg_controller_en", "leg_controller_reset"]

    __typenames__ = ["boolean", "boolean", "boolean", "boolean"]

    __dimensions__ = [None, None, None, None]

    def __init__(self):
        self.locomotion_en = False
        self.locomotion_reset = False
        self.leg_controller_en = False
        self.leg_controller_reset = False

    def encode(self):
        buf = BytesIO()
        buf.write(enable_msg._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">bbbb", self.locomotion_en, self.locomotion_reset, self.leg_controller_en, self.leg_controller_reset))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != enable_msg._get_packed_fingerprint():
            raise ValueError("Decode error")
        return enable_msg._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = enable_msg()
        self.locomotion_en = bool(struct.unpack('b', buf.read(1))[0])
        self.locomotion_reset = bool(struct.unpack('b', buf.read(1))[0])
        self.leg_controller_en = bool(struct.unpack('b', buf.read(1))[0])
        self.leg_controller_reset = bool(struct.unpack('b', buf.read(1))[0])
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if enable_msg in parents: return 0
        tmphash = (0xdc18d695cfbcfdc5) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if enable_msg._packed_fingerprint is None:
            enable_msg._packed_fingerprint = struct.pack(">Q", enable_msg._get_hash_recursive([]))
        return enable_msg._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", enable_msg._get_packed_fingerprint())[0]

