/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package mors_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class enable_msg implements lcm.lcm.LCMEncodable
{
    public boolean locomotion_en;
    public boolean locomotion_reset;
    public boolean leg_controller_en;
    public boolean leg_controller_reset;
 
    public enable_msg()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xdc18d695cfbcfdc5L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(mors_msgs.enable_msg.class))
            return 0L;
 
        classes.add(mors_msgs.enable_msg.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeByte( this.locomotion_en ? 1 : 0); 
 
        outs.writeByte( this.locomotion_reset ? 1 : 0); 
 
        outs.writeByte( this.leg_controller_en ? 1 : 0); 
 
        outs.writeByte( this.leg_controller_reset ? 1 : 0); 
 
    }
 
    public enable_msg(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public enable_msg(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static mors_msgs.enable_msg _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        mors_msgs.enable_msg o = new mors_msgs.enable_msg();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.locomotion_en = ins.readByte()!=0;
 
        this.locomotion_reset = ins.readByte()!=0;
 
        this.leg_controller_en = ins.readByte()!=0;
 
        this.leg_controller_reset = ins.readByte()!=0;
 
    }
 
    public mors_msgs.enable_msg copy()
    {
        mors_msgs.enable_msg outobj = new mors_msgs.enable_msg();
        outobj.locomotion_en = this.locomotion_en;
 
        outobj.locomotion_reset = this.locomotion_reset;
 
        outobj.leg_controller_en = this.leg_controller_en;
 
        outobj.leg_controller_reset = this.leg_controller_reset;
 
        return outobj;
    }
 
}

