/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package mors_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class foot_cmd_msg implements lcm.lcm.LCMEncodable
{
    public double r1_pos[];
    public double l1_pos[];
    public double r2_pos[];
    public double l2_pos[];
    public double r1_vel[];
    public double l1_vel[];
    public double r2_vel[];
    public double l2_vel[];
    public double r1_acc[];
    public double l1_acc[];
    public double r2_acc[];
    public double l2_acc[];
    public double r1_kp[];
    public double l1_kp[];
    public double r2_kp[];
    public double l2_kp[];
    public double r1_kd[];
    public double l1_kd[];
    public double r2_kd[];
    public double l2_kd[];
 
    public foot_cmd_msg()
    {
        r1_pos = new double[3];
        l1_pos = new double[3];
        r2_pos = new double[3];
        l2_pos = new double[3];
        r1_vel = new double[3];
        l1_vel = new double[3];
        r2_vel = new double[3];
        l2_vel = new double[3];
        r1_acc = new double[3];
        l1_acc = new double[3];
        r2_acc = new double[3];
        l2_acc = new double[3];
        r1_kp = new double[3];
        l1_kp = new double[3];
        r2_kp = new double[3];
        l2_kp = new double[3];
        r1_kd = new double[3];
        l1_kd = new double[3];
        r2_kd = new double[3];
        l2_kd = new double[3];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x3cd6a96b0a9661cbL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(mors_msgs.foot_cmd_msg.class))
            return 0L;
 
        classes.add(mors_msgs.foot_cmd_msg.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.r1_pos[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.l1_pos[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.r2_pos[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.l2_pos[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.r1_vel[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.l1_vel[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.r2_vel[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.l2_vel[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.r1_acc[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.l1_acc[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.r2_acc[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.l2_acc[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.r1_kp[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.l1_kp[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.r2_kp[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.l2_kp[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.r1_kd[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.l1_kd[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.r2_kd[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.l2_kd[a]); 
        }
 
    }
 
    public foot_cmd_msg(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public foot_cmd_msg(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static mors_msgs.foot_cmd_msg _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        mors_msgs.foot_cmd_msg o = new mors_msgs.foot_cmd_msg();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.r1_pos = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.r1_pos[a] = ins.readDouble();
        }
 
        this.l1_pos = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.l1_pos[a] = ins.readDouble();
        }
 
        this.r2_pos = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.r2_pos[a] = ins.readDouble();
        }
 
        this.l2_pos = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.l2_pos[a] = ins.readDouble();
        }
 
        this.r1_vel = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.r1_vel[a] = ins.readDouble();
        }
 
        this.l1_vel = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.l1_vel[a] = ins.readDouble();
        }
 
        this.r2_vel = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.r2_vel[a] = ins.readDouble();
        }
 
        this.l2_vel = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.l2_vel[a] = ins.readDouble();
        }
 
        this.r1_acc = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.r1_acc[a] = ins.readDouble();
        }
 
        this.l1_acc = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.l1_acc[a] = ins.readDouble();
        }
 
        this.r2_acc = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.r2_acc[a] = ins.readDouble();
        }
 
        this.l2_acc = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.l2_acc[a] = ins.readDouble();
        }
 
        this.r1_kp = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.r1_kp[a] = ins.readDouble();
        }
 
        this.l1_kp = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.l1_kp[a] = ins.readDouble();
        }
 
        this.r2_kp = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.r2_kp[a] = ins.readDouble();
        }
 
        this.l2_kp = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.l2_kp[a] = ins.readDouble();
        }
 
        this.r1_kd = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.r1_kd[a] = ins.readDouble();
        }
 
        this.l1_kd = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.l1_kd[a] = ins.readDouble();
        }
 
        this.r2_kd = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.r2_kd[a] = ins.readDouble();
        }
 
        this.l2_kd = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.l2_kd[a] = ins.readDouble();
        }
 
    }
 
    public mors_msgs.foot_cmd_msg copy()
    {
        mors_msgs.foot_cmd_msg outobj = new mors_msgs.foot_cmd_msg();
        outobj.r1_pos = new double[(int) 3];
        System.arraycopy(this.r1_pos, 0, outobj.r1_pos, 0, 3); 
        outobj.l1_pos = new double[(int) 3];
        System.arraycopy(this.l1_pos, 0, outobj.l1_pos, 0, 3); 
        outobj.r2_pos = new double[(int) 3];
        System.arraycopy(this.r2_pos, 0, outobj.r2_pos, 0, 3); 
        outobj.l2_pos = new double[(int) 3];
        System.arraycopy(this.l2_pos, 0, outobj.l2_pos, 0, 3); 
        outobj.r1_vel = new double[(int) 3];
        System.arraycopy(this.r1_vel, 0, outobj.r1_vel, 0, 3); 
        outobj.l1_vel = new double[(int) 3];
        System.arraycopy(this.l1_vel, 0, outobj.l1_vel, 0, 3); 
        outobj.r2_vel = new double[(int) 3];
        System.arraycopy(this.r2_vel, 0, outobj.r2_vel, 0, 3); 
        outobj.l2_vel = new double[(int) 3];
        System.arraycopy(this.l2_vel, 0, outobj.l2_vel, 0, 3); 
        outobj.r1_acc = new double[(int) 3];
        System.arraycopy(this.r1_acc, 0, outobj.r1_acc, 0, 3); 
        outobj.l1_acc = new double[(int) 3];
        System.arraycopy(this.l1_acc, 0, outobj.l1_acc, 0, 3); 
        outobj.r2_acc = new double[(int) 3];
        System.arraycopy(this.r2_acc, 0, outobj.r2_acc, 0, 3); 
        outobj.l2_acc = new double[(int) 3];
        System.arraycopy(this.l2_acc, 0, outobj.l2_acc, 0, 3); 
        outobj.r1_kp = new double[(int) 3];
        System.arraycopy(this.r1_kp, 0, outobj.r1_kp, 0, 3); 
        outobj.l1_kp = new double[(int) 3];
        System.arraycopy(this.l1_kp, 0, outobj.l1_kp, 0, 3); 
        outobj.r2_kp = new double[(int) 3];
        System.arraycopy(this.r2_kp, 0, outobj.r2_kp, 0, 3); 
        outobj.l2_kp = new double[(int) 3];
        System.arraycopy(this.l2_kp, 0, outobj.l2_kp, 0, 3); 
        outobj.r1_kd = new double[(int) 3];
        System.arraycopy(this.r1_kd, 0, outobj.r1_kd, 0, 3); 
        outobj.l1_kd = new double[(int) 3];
        System.arraycopy(this.l1_kd, 0, outobj.l1_kd, 0, 3); 
        outobj.r2_kd = new double[(int) 3];
        System.arraycopy(this.r2_kd, 0, outobj.r2_kd, 0, 3); 
        outobj.l2_kd = new double[(int) 3];
        System.arraycopy(this.l2_kd, 0, outobj.l2_kd, 0, 3); 
        return outobj;
    }
 
}

