"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class foot_cmd_msg(object):
    __slots__ = ["r1_pos", "l1_pos", "r2_pos", "l2_pos", "r1_vel", "l1_vel", "r2_vel", "l2_vel", "r1_acc", "l1_acc", "r2_acc", "l2_acc", "r1_kp", "l1_kp", "r2_kp", "l2_kp", "r1_kd", "l1_kd", "r2_kd", "l2_kd"]

    __typenames__ = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"]

    __dimensions__ = [[3], [3], [3], [3], [3], [3], [3], [3], [3], [3], [3], [3], [3], [3], [3], [3], [3], [3], [3], [3]]

    def __init__(self):
        self.r1_pos = [ 0.0 for dim0 in range(3) ]
        self.l1_pos = [ 0.0 for dim0 in range(3) ]
        self.r2_pos = [ 0.0 for dim0 in range(3) ]
        self.l2_pos = [ 0.0 for dim0 in range(3) ]
        self.r1_vel = [ 0.0 for dim0 in range(3) ]
        self.l1_vel = [ 0.0 for dim0 in range(3) ]
        self.r2_vel = [ 0.0 for dim0 in range(3) ]
        self.l2_vel = [ 0.0 for dim0 in range(3) ]
        self.r1_acc = [ 0.0 for dim0 in range(3) ]
        self.l1_acc = [ 0.0 for dim0 in range(3) ]
        self.r2_acc = [ 0.0 for dim0 in range(3) ]
        self.l2_acc = [ 0.0 for dim0 in range(3) ]
        self.r1_kp = [ 0.0 for dim0 in range(3) ]
        self.l1_kp = [ 0.0 for dim0 in range(3) ]
        self.r2_kp = [ 0.0 for dim0 in range(3) ]
        self.l2_kp = [ 0.0 for dim0 in range(3) ]
        self.r1_kd = [ 0.0 for dim0 in range(3) ]
        self.l1_kd = [ 0.0 for dim0 in range(3) ]
        self.r2_kd = [ 0.0 for dim0 in range(3) ]
        self.l2_kd = [ 0.0 for dim0 in range(3) ]

    def encode(self):
        buf = BytesIO()
        buf.write(foot_cmd_msg._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>3d', *self.r1_pos[:3]))
        buf.write(struct.pack('>3d', *self.l1_pos[:3]))
        buf.write(struct.pack('>3d', *self.r2_pos[:3]))
        buf.write(struct.pack('>3d', *self.l2_pos[:3]))
        buf.write(struct.pack('>3d', *self.r1_vel[:3]))
        buf.write(struct.pack('>3d', *self.l1_vel[:3]))
        buf.write(struct.pack('>3d', *self.r2_vel[:3]))
        buf.write(struct.pack('>3d', *self.l2_vel[:3]))
        buf.write(struct.pack('>3d', *self.r1_acc[:3]))
        buf.write(struct.pack('>3d', *self.l1_acc[:3]))
        buf.write(struct.pack('>3d', *self.r2_acc[:3]))
        buf.write(struct.pack('>3d', *self.l2_acc[:3]))
        buf.write(struct.pack('>3d', *self.r1_kp[:3]))
        buf.write(struct.pack('>3d', *self.l1_kp[:3]))
        buf.write(struct.pack('>3d', *self.r2_kp[:3]))
        buf.write(struct.pack('>3d', *self.l2_kp[:3]))
        buf.write(struct.pack('>3d', *self.r1_kd[:3]))
        buf.write(struct.pack('>3d', *self.l1_kd[:3]))
        buf.write(struct.pack('>3d', *self.r2_kd[:3]))
        buf.write(struct.pack('>3d', *self.l2_kd[:3]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != foot_cmd_msg._get_packed_fingerprint():
            raise ValueError("Decode error")
        return foot_cmd_msg._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = foot_cmd_msg()
        self.r1_pos = struct.unpack('>3d', buf.read(24))
        self.l1_pos = struct.unpack('>3d', buf.read(24))
        self.r2_pos = struct.unpack('>3d', buf.read(24))
        self.l2_pos = struct.unpack('>3d', buf.read(24))
        self.r1_vel = struct.unpack('>3d', buf.read(24))
        self.l1_vel = struct.unpack('>3d', buf.read(24))
        self.r2_vel = struct.unpack('>3d', buf.read(24))
        self.l2_vel = struct.unpack('>3d', buf.read(24))
        self.r1_acc = struct.unpack('>3d', buf.read(24))
        self.l1_acc = struct.unpack('>3d', buf.read(24))
        self.r2_acc = struct.unpack('>3d', buf.read(24))
        self.l2_acc = struct.unpack('>3d', buf.read(24))
        self.r1_kp = struct.unpack('>3d', buf.read(24))
        self.l1_kp = struct.unpack('>3d', buf.read(24))
        self.r2_kp = struct.unpack('>3d', buf.read(24))
        self.l2_kp = struct.unpack('>3d', buf.read(24))
        self.r1_kd = struct.unpack('>3d', buf.read(24))
        self.l1_kd = struct.unpack('>3d', buf.read(24))
        self.r2_kd = struct.unpack('>3d', buf.read(24))
        self.l2_kd = struct.unpack('>3d', buf.read(24))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if foot_cmd_msg in parents: return 0
        tmphash = (0x3cd6a96b0a9661cb) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if foot_cmd_msg._packed_fingerprint is None:
            foot_cmd_msg._packed_fingerprint = struct.pack(">Q", foot_cmd_msg._get_hash_recursive([]))
        return foot_cmd_msg._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", foot_cmd_msg._get_packed_fingerprint())[0]

