"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class gait_params_msg(object):
    __slots__ = ["standing", "gait_type", "t_sw", "t_st", "stride_height"]

    __typenames__ = ["boolean", "float", "float", "float", "float"]

    __dimensions__ = [None, [4], None, None, None]

    def __init__(self):
        self.standing = False
        self.gait_type = [ 0.0 for dim0 in range(4) ]
        self.t_sw = 0.0
        self.t_st = 0.0
        self.stride_height = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(gait_params_msg._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">b", self.standing))
        buf.write(struct.pack('>4f', *self.gait_type[:4]))
        buf.write(struct.pack(">fff", self.t_sw, self.t_st, self.stride_height))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != gait_params_msg._get_packed_fingerprint():
            raise ValueError("Decode error")
        return gait_params_msg._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = gait_params_msg()
        self.standing = bool(struct.unpack('b', buf.read(1))[0])
        self.gait_type = struct.unpack('>4f', buf.read(16))
        self.t_sw, self.t_st, self.stride_height = struct.unpack(">fff", buf.read(12))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if gait_params_msg in parents: return 0
        tmphash = (0xb46c82b728b582cf) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if gait_params_msg._packed_fingerprint is None:
            gait_params_msg._packed_fingerprint = struct.pack(">Q", gait_params_msg._get_hash_recursive([]))
        return gait_params_msg._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", gait_params_msg._get_packed_fingerprint())[0]

