/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package mors_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class gait_params_msg implements lcm.lcm.LCMEncodable
{
    public boolean standing;
    public float gait_type[];
    public float t_sw;
    public float t_st;
    public float stride_height;
 
    public gait_params_msg()
    {
        gait_type = new float[4];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xb46c82b728b582cfL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(mors_msgs.gait_params_msg.class))
            return 0L;
 
        classes.add(mors_msgs.gait_params_msg.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeByte( this.standing ? 1 : 0); 
 
        for (int a = 0; a < 4; a++) {
            outs.writeFloat(this.gait_type[a]); 
        }
 
        outs.writeFloat(this.t_sw); 
 
        outs.writeFloat(this.t_st); 
 
        outs.writeFloat(this.stride_height); 
 
    }
 
    public gait_params_msg(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public gait_params_msg(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static mors_msgs.gait_params_msg _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        mors_msgs.gait_params_msg o = new mors_msgs.gait_params_msg();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.standing = ins.readByte()!=0;
 
        this.gait_type = new float[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.gait_type[a] = ins.readFloat();
        }
 
        this.t_sw = ins.readFloat();
 
        this.t_st = ins.readFloat();
 
        this.stride_height = ins.readFloat();
 
    }
 
    public mors_msgs.gait_params_msg copy()
    {
        mors_msgs.gait_params_msg outobj = new mors_msgs.gait_params_msg();
        outobj.standing = this.standing;
 
        outobj.gait_type = new float[(int) 4];
        System.arraycopy(this.gait_type, 0, outobj.gait_type, 0, 4); 
        outobj.t_sw = this.t_sw;
 
        outobj.t_st = this.t_st;
 
        outobj.stride_height = this.stride_height;
 
        return outobj;
    }
 
}

