"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class grf_cmd_msg(object):
    __slots__ = ["r1_grf", "l1_grf", "r2_grf", "l2_grf"]

    __typenames__ = ["double", "double", "double", "double"]

    __dimensions__ = [[3], [3], [3], [3]]

    def __init__(self):
        self.r1_grf = [ 0.0 for dim0 in range(3) ]
        self.l1_grf = [ 0.0 for dim0 in range(3) ]
        self.r2_grf = [ 0.0 for dim0 in range(3) ]
        self.l2_grf = [ 0.0 for dim0 in range(3) ]

    def encode(self):
        buf = BytesIO()
        buf.write(grf_cmd_msg._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>3d', *self.r1_grf[:3]))
        buf.write(struct.pack('>3d', *self.l1_grf[:3]))
        buf.write(struct.pack('>3d', *self.r2_grf[:3]))
        buf.write(struct.pack('>3d', *self.l2_grf[:3]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != grf_cmd_msg._get_packed_fingerprint():
            raise ValueError("Decode error")
        return grf_cmd_msg._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = grf_cmd_msg()
        self.r1_grf = struct.unpack('>3d', buf.read(24))
        self.l1_grf = struct.unpack('>3d', buf.read(24))
        self.r2_grf = struct.unpack('>3d', buf.read(24))
        self.l2_grf = struct.unpack('>3d', buf.read(24))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if grf_cmd_msg in parents: return 0
        tmphash = (0xf785bfc3f533ad3) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if grf_cmd_msg._packed_fingerprint is None:
            grf_cmd_msg._packed_fingerprint = struct.pack(">Q", grf_cmd_msg._get_hash_recursive([]))
        return grf_cmd_msg._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", grf_cmd_msg._get_packed_fingerprint())[0]

