/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package mors_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class grf_cmd_msg implements lcm.lcm.LCMEncodable
{
    public double r1_grf[];
    public double l1_grf[];
    public double r2_grf[];
    public double l2_grf[];
 
    public grf_cmd_msg()
    {
        r1_grf = new double[3];
        l1_grf = new double[3];
        r2_grf = new double[3];
        l2_grf = new double[3];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x0f785bfc3f533ad3L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(mors_msgs.grf_cmd_msg.class))
            return 0L;
 
        classes.add(mors_msgs.grf_cmd_msg.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.r1_grf[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.l1_grf[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.r2_grf[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.l2_grf[a]); 
        }
 
    }
 
    public grf_cmd_msg(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public grf_cmd_msg(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static mors_msgs.grf_cmd_msg _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        mors_msgs.grf_cmd_msg o = new mors_msgs.grf_cmd_msg();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.r1_grf = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.r1_grf[a] = ins.readDouble();
        }
 
        this.l1_grf = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.l1_grf[a] = ins.readDouble();
        }
 
        this.r2_grf = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.r2_grf[a] = ins.readDouble();
        }
 
        this.l2_grf = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.l2_grf[a] = ins.readDouble();
        }
 
    }
 
    public mors_msgs.grf_cmd_msg copy()
    {
        mors_msgs.grf_cmd_msg outobj = new mors_msgs.grf_cmd_msg();
        outobj.r1_grf = new double[(int) 3];
        System.arraycopy(this.r1_grf, 0, outobj.r1_grf, 0, 3); 
        outobj.l1_grf = new double[(int) 3];
        System.arraycopy(this.l1_grf, 0, outobj.l1_grf, 0, 3); 
        outobj.r2_grf = new double[(int) 3];
        System.arraycopy(this.r2_grf, 0, outobj.r2_grf, 0, 3); 
        outobj.l2_grf = new double[(int) 3];
        System.arraycopy(this.l2_grf, 0, outobj.l2_grf, 0, 3); 
        return outobj;
    }
 
}

