"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class height_map_msg(object):
    __slots__ = ["timestamp", "center_x", "center_y", "robot_yaw", "resolution", "width", "height", "data"]

    __typenames__ = ["int64_t", "float", "float", "float", "float", "int32_t", "int32_t", "float"]

    __dimensions__ = [None, None, None, None, None, None, None, ["height", "width"]]

    def __init__(self):
        self.timestamp = 0
        self.center_x = 0.0
        self.center_y = 0.0
        self.robot_yaw = 0.0
        self.resolution = 0.0
        self.width = 0
        self.height = 0
        self.data = []

    def encode(self):
        buf = BytesIO()
        buf.write(height_map_msg._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qffffii", self.timestamp, self.center_x, self.center_y, self.robot_yaw, self.resolution, self.width, self.height))
        for i0 in range(self.height):
            buf.write(struct.pack('>%df' % self.width, *self.data[i0][:self.width]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != height_map_msg._get_packed_fingerprint():
            raise ValueError("Decode error")
        return height_map_msg._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = height_map_msg()
        self.timestamp, self.center_x, self.center_y, self.robot_yaw, self.resolution, self.width, self.height = struct.unpack(">qffffii", buf.read(32))
        self.data = []
        for i0 in range(self.height):
            self.data.append(struct.unpack('>%df' % self.width, buf.read(self.width * 4)))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if height_map_msg in parents: return 0
        tmphash = (0x8893eaca41e88c05) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if height_map_msg._packed_fingerprint is None:
            height_map_msg._packed_fingerprint = struct.pack(">Q", height_map_msg._get_hash_recursive([]))
        return height_map_msg._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", height_map_msg._get_packed_fingerprint())[0]

