/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package mors_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class height_map_msg implements lcm.lcm.LCMEncodable
{
    public long timestamp;
    public float center_x;
    public float center_y;
    public float robot_yaw;
    public float resolution;
    public int width;
    public int height;
    public float data[][];
 
    public height_map_msg()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x8893eaca41e88c05L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(mors_msgs.height_map_msg.class))
            return 0L;
 
        classes.add(mors_msgs.height_map_msg.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.timestamp); 
 
        outs.writeFloat(this.center_x); 
 
        outs.writeFloat(this.center_y); 
 
        outs.writeFloat(this.robot_yaw); 
 
        outs.writeFloat(this.resolution); 
 
        outs.writeInt(this.width); 
 
        outs.writeInt(this.height); 
 
        for (int a = 0; a < this.height; a++) {
            for (int b = 0; b < this.width; b++) {
                outs.writeFloat(this.data[a][b]); 
            }
        }
 
    }
 
    public height_map_msg(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public height_map_msg(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static mors_msgs.height_map_msg _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        mors_msgs.height_map_msg o = new mors_msgs.height_map_msg();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.timestamp = ins.readLong();
 
        this.center_x = ins.readFloat();
 
        this.center_y = ins.readFloat();
 
        this.robot_yaw = ins.readFloat();
 
        this.resolution = ins.readFloat();
 
        this.width = ins.readInt();
 
        this.height = ins.readInt();
 
        this.data = new float[(int) height][(int) width];
        for (int a = 0; a < this.height; a++) {
            for (int b = 0; b < this.width; b++) {
                this.data[a][b] = ins.readFloat();
            }
        }
 
    }
 
    public mors_msgs.height_map_msg copy()
    {
        mors_msgs.height_map_msg outobj = new mors_msgs.height_map_msg();
        outobj.timestamp = this.timestamp;
 
        outobj.center_x = this.center_x;
 
        outobj.center_y = this.center_y;
 
        outobj.robot_yaw = this.robot_yaw;
 
        outobj.resolution = this.resolution;
 
        outobj.width = this.width;
 
        outobj.height = this.height;
 
        outobj.data = new float[(int) height][(int) width];
        for (int a = 0; a < this.height; a++) {
            if (this.width > 0)
                System.arraycopy(this.data[a], 0, outobj.data[a], 0, (int) this.width);        }
 
        return outobj;
    }
 
}

