/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package mors_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class imu_lcm_data implements lcm.lcm.LCMEncodable
{
    public float orientation_quaternion[];
    public float orientation_euler[];
    public float orientation_covariance[];
    public float angular_velocity[];
    public float angular_velocity_covariance[];
    public float linear_acceleration[];
    public float linear_acceleration_covariance[];
    public float magnetic_field[];
    public float magnetic_field_covariance[];
    public float temperature;
    public float temperature_variance;
 
    public imu_lcm_data()
    {
        orientation_quaternion = new float[4];
        orientation_euler = new float[3];
        orientation_covariance = new float[9];
        angular_velocity = new float[3];
        angular_velocity_covariance = new float[9];
        linear_acceleration = new float[3];
        linear_acceleration_covariance = new float[9];
        magnetic_field = new float[3];
        magnetic_field_covariance = new float[9];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xe6edfaee2aa2bd8fL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(mors_msgs.imu_lcm_data.class))
            return 0L;
 
        classes.add(mors_msgs.imu_lcm_data.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        for (int a = 0; a < 4; a++) {
            outs.writeFloat(this.orientation_quaternion[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.orientation_euler[a]); 
        }
 
        for (int a = 0; a < 9; a++) {
            outs.writeFloat(this.orientation_covariance[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.angular_velocity[a]); 
        }
 
        for (int a = 0; a < 9; a++) {
            outs.writeFloat(this.angular_velocity_covariance[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.linear_acceleration[a]); 
        }
 
        for (int a = 0; a < 9; a++) {
            outs.writeFloat(this.linear_acceleration_covariance[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.magnetic_field[a]); 
        }
 
        for (int a = 0; a < 9; a++) {
            outs.writeFloat(this.magnetic_field_covariance[a]); 
        }
 
        outs.writeFloat(this.temperature); 
 
        outs.writeFloat(this.temperature_variance); 
 
    }
 
    public imu_lcm_data(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public imu_lcm_data(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static mors_msgs.imu_lcm_data _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        mors_msgs.imu_lcm_data o = new mors_msgs.imu_lcm_data();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.orientation_quaternion = new float[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.orientation_quaternion[a] = ins.readFloat();
        }
 
        this.orientation_euler = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.orientation_euler[a] = ins.readFloat();
        }
 
        this.orientation_covariance = new float[(int) 9];
        for (int a = 0; a < 9; a++) {
            this.orientation_covariance[a] = ins.readFloat();
        }
 
        this.angular_velocity = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.angular_velocity[a] = ins.readFloat();
        }
 
        this.angular_velocity_covariance = new float[(int) 9];
        for (int a = 0; a < 9; a++) {
            this.angular_velocity_covariance[a] = ins.readFloat();
        }
 
        this.linear_acceleration = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.linear_acceleration[a] = ins.readFloat();
        }
 
        this.linear_acceleration_covariance = new float[(int) 9];
        for (int a = 0; a < 9; a++) {
            this.linear_acceleration_covariance[a] = ins.readFloat();
        }
 
        this.magnetic_field = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.magnetic_field[a] = ins.readFloat();
        }
 
        this.magnetic_field_covariance = new float[(int) 9];
        for (int a = 0; a < 9; a++) {
            this.magnetic_field_covariance[a] = ins.readFloat();
        }
 
        this.temperature = ins.readFloat();
 
        this.temperature_variance = ins.readFloat();
 
    }
 
    public mors_msgs.imu_lcm_data copy()
    {
        mors_msgs.imu_lcm_data outobj = new mors_msgs.imu_lcm_data();
        outobj.orientation_quaternion = new float[(int) 4];
        System.arraycopy(this.orientation_quaternion, 0, outobj.orientation_quaternion, 0, 4); 
        outobj.orientation_euler = new float[(int) 3];
        System.arraycopy(this.orientation_euler, 0, outobj.orientation_euler, 0, 3); 
        outobj.orientation_covariance = new float[(int) 9];
        System.arraycopy(this.orientation_covariance, 0, outobj.orientation_covariance, 0, 9); 
        outobj.angular_velocity = new float[(int) 3];
        System.arraycopy(this.angular_velocity, 0, outobj.angular_velocity, 0, 3); 
        outobj.angular_velocity_covariance = new float[(int) 9];
        System.arraycopy(this.angular_velocity_covariance, 0, outobj.angular_velocity_covariance, 0, 9); 
        outobj.linear_acceleration = new float[(int) 3];
        System.arraycopy(this.linear_acceleration, 0, outobj.linear_acceleration, 0, 3); 
        outobj.linear_acceleration_covariance = new float[(int) 9];
        System.arraycopy(this.linear_acceleration_covariance, 0, outobj.linear_acceleration_covariance, 0, 9); 
        outobj.magnetic_field = new float[(int) 3];
        System.arraycopy(this.magnetic_field, 0, outobj.magnetic_field, 0, 3); 
        outobj.magnetic_field_covariance = new float[(int) 9];
        System.arraycopy(this.magnetic_field_covariance, 0, outobj.magnetic_field_covariance, 0, 9); 
        outobj.temperature = this.temperature;
 
        outobj.temperature_variance = this.temperature_variance;
 
        return outobj;
    }
 
}

