/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package mors_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class leg_cmd_msg implements lcm.lcm.LCMEncodable
{
    public boolean imp_mode[];
    public boolean grf_mode[];
    public double r1_pos[];
    public double l1_pos[];
    public double r2_pos[];
    public double l2_pos[];
    public double r1_vel[];
    public double l1_vel[];
    public double r2_vel[];
    public double l2_vel[];
    public double r1_grf[];
    public double l1_grf[];
    public double r2_grf[];
    public double l2_grf[];
    public double Kp[];
    public double Kd[];
 
    public leg_cmd_msg()
    {
        imp_mode = new boolean[4];
        grf_mode = new boolean[4];
        r1_pos = new double[3];
        l1_pos = new double[3];
        r2_pos = new double[3];
        l2_pos = new double[3];
        r1_vel = new double[3];
        l1_vel = new double[3];
        r2_vel = new double[3];
        l2_vel = new double[3];
        r1_grf = new double[3];
        l1_grf = new double[3];
        r2_grf = new double[3];
        l2_grf = new double[3];
        Kp = new double[3];
        Kd = new double[3];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x97384aff7a1d4f05L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(mors_msgs.leg_cmd_msg.class))
            return 0L;
 
        classes.add(mors_msgs.leg_cmd_msg.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        for (int a = 0; a < 4; a++) {
            outs.writeByte( this.imp_mode[a] ? 1 : 0); 
        }
 
        for (int a = 0; a < 4; a++) {
            outs.writeByte( this.grf_mode[a] ? 1 : 0); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.r1_pos[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.l1_pos[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.r2_pos[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.l2_pos[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.r1_vel[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.l1_vel[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.r2_vel[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.l2_vel[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.r1_grf[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.l1_grf[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.r2_grf[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.l2_grf[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.Kp[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.Kd[a]); 
        }
 
    }
 
    public leg_cmd_msg(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public leg_cmd_msg(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static mors_msgs.leg_cmd_msg _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        mors_msgs.leg_cmd_msg o = new mors_msgs.leg_cmd_msg();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.imp_mode = new boolean[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.imp_mode[a] = ins.readByte()!=0;
        }
 
        this.grf_mode = new boolean[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.grf_mode[a] = ins.readByte()!=0;
        }
 
        this.r1_pos = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.r1_pos[a] = ins.readDouble();
        }
 
        this.l1_pos = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.l1_pos[a] = ins.readDouble();
        }
 
        this.r2_pos = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.r2_pos[a] = ins.readDouble();
        }
 
        this.l2_pos = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.l2_pos[a] = ins.readDouble();
        }
 
        this.r1_vel = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.r1_vel[a] = ins.readDouble();
        }
 
        this.l1_vel = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.l1_vel[a] = ins.readDouble();
        }
 
        this.r2_vel = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.r2_vel[a] = ins.readDouble();
        }
 
        this.l2_vel = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.l2_vel[a] = ins.readDouble();
        }
 
        this.r1_grf = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.r1_grf[a] = ins.readDouble();
        }
 
        this.l1_grf = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.l1_grf[a] = ins.readDouble();
        }
 
        this.r2_grf = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.r2_grf[a] = ins.readDouble();
        }
 
        this.l2_grf = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.l2_grf[a] = ins.readDouble();
        }
 
        this.Kp = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.Kp[a] = ins.readDouble();
        }
 
        this.Kd = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.Kd[a] = ins.readDouble();
        }
 
    }
 
    public mors_msgs.leg_cmd_msg copy()
    {
        mors_msgs.leg_cmd_msg outobj = new mors_msgs.leg_cmd_msg();
        outobj.imp_mode = new boolean[(int) 4];
        System.arraycopy(this.imp_mode, 0, outobj.imp_mode, 0, 4); 
        outobj.grf_mode = new boolean[(int) 4];
        System.arraycopy(this.grf_mode, 0, outobj.grf_mode, 0, 4); 
        outobj.r1_pos = new double[(int) 3];
        System.arraycopy(this.r1_pos, 0, outobj.r1_pos, 0, 3); 
        outobj.l1_pos = new double[(int) 3];
        System.arraycopy(this.l1_pos, 0, outobj.l1_pos, 0, 3); 
        outobj.r2_pos = new double[(int) 3];
        System.arraycopy(this.r2_pos, 0, outobj.r2_pos, 0, 3); 
        outobj.l2_pos = new double[(int) 3];
        System.arraycopy(this.l2_pos, 0, outobj.l2_pos, 0, 3); 
        outobj.r1_vel = new double[(int) 3];
        System.arraycopy(this.r1_vel, 0, outobj.r1_vel, 0, 3); 
        outobj.l1_vel = new double[(int) 3];
        System.arraycopy(this.l1_vel, 0, outobj.l1_vel, 0, 3); 
        outobj.r2_vel = new double[(int) 3];
        System.arraycopy(this.r2_vel, 0, outobj.r2_vel, 0, 3); 
        outobj.l2_vel = new double[(int) 3];
        System.arraycopy(this.l2_vel, 0, outobj.l2_vel, 0, 3); 
        outobj.r1_grf = new double[(int) 3];
        System.arraycopy(this.r1_grf, 0, outobj.r1_grf, 0, 3); 
        outobj.l1_grf = new double[(int) 3];
        System.arraycopy(this.l1_grf, 0, outobj.l1_grf, 0, 3); 
        outobj.r2_grf = new double[(int) 3];
        System.arraycopy(this.r2_grf, 0, outobj.r2_grf, 0, 3); 
        outobj.l2_grf = new double[(int) 3];
        System.arraycopy(this.l2_grf, 0, outobj.l2_grf, 0, 3); 
        outobj.Kp = new double[(int) 3];
        System.arraycopy(this.Kp, 0, outobj.Kp, 0, 3); 
        outobj.Kd = new double[(int) 3];
        System.arraycopy(this.Kd, 0, outobj.Kd, 0, 3); 
        return outobj;
    }
 
}

