"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class mpc_cmd_msg(object):
    __slots__ = ["cmd_pose", "cmd_vel", "active_legs"]

    __typenames__ = ["float", "float", "boolean"]

    __dimensions__ = [[6], [6], [4]]

    def __init__(self):
        self.cmd_pose = [ 0.0 for dim0 in range(6) ]
        self.cmd_vel = [ 0.0 for dim0 in range(6) ]
        self.active_legs = [ False for dim0 in range(4) ]

    def encode(self):
        buf = BytesIO()
        buf.write(mpc_cmd_msg._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>6f', *self.cmd_pose[:6]))
        buf.write(struct.pack('>6f', *self.cmd_vel[:6]))
        buf.write(struct.pack('>4b', *self.active_legs[:4]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != mpc_cmd_msg._get_packed_fingerprint():
            raise ValueError("Decode error")
        return mpc_cmd_msg._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = mpc_cmd_msg()
        self.cmd_pose = struct.unpack('>6f', buf.read(24))
        self.cmd_vel = struct.unpack('>6f', buf.read(24))
        self.active_legs = [bool(x) for x in struct.unpack('>4b', buf.read(4))]
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if mpc_cmd_msg in parents: return 0
        tmphash = (0x97621a033a71b19d) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if mpc_cmd_msg._packed_fingerprint is None:
            mpc_cmd_msg._packed_fingerprint = struct.pack(">Q", mpc_cmd_msg._get_hash_recursive([]))
        return mpc_cmd_msg._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", mpc_cmd_msg._get_packed_fingerprint())[0]

