/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package mors_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class odometry_msg implements lcm.lcm.LCMEncodable
{
    public float position[];
    public float orientation[];
    public float orientation_quaternion[];
    public float lin_vel[];
    public float ang_vel[];
 
    public odometry_msg()
    {
        position = new float[3];
        orientation = new float[3];
        orientation_quaternion = new float[4];
        lin_vel = new float[3];
        ang_vel = new float[3];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xe6bb50a46c73bed8L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(mors_msgs.odometry_msg.class))
            return 0L;
 
        classes.add(mors_msgs.odometry_msg.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.position[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.orientation[a]); 
        }
 
        for (int a = 0; a < 4; a++) {
            outs.writeFloat(this.orientation_quaternion[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.lin_vel[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.ang_vel[a]); 
        }
 
    }
 
    public odometry_msg(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public odometry_msg(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static mors_msgs.odometry_msg _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        mors_msgs.odometry_msg o = new mors_msgs.odometry_msg();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.position = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.position[a] = ins.readFloat();
        }
 
        this.orientation = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.orientation[a] = ins.readFloat();
        }
 
        this.orientation_quaternion = new float[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.orientation_quaternion[a] = ins.readFloat();
        }
 
        this.lin_vel = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.lin_vel[a] = ins.readFloat();
        }
 
        this.ang_vel = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.ang_vel[a] = ins.readFloat();
        }
 
    }
 
    public mors_msgs.odometry_msg copy()
    {
        mors_msgs.odometry_msg outobj = new mors_msgs.odometry_msg();
        outobj.position = new float[(int) 3];
        System.arraycopy(this.position, 0, outobj.position, 0, 3); 
        outobj.orientation = new float[(int) 3];
        System.arraycopy(this.orientation, 0, outobj.orientation, 0, 3); 
        outobj.orientation_quaternion = new float[(int) 4];
        System.arraycopy(this.orientation_quaternion, 0, outobj.orientation_quaternion, 0, 4); 
        outobj.lin_vel = new float[(int) 3];
        System.arraycopy(this.lin_vel, 0, outobj.lin_vel, 0, 3); 
        outobj.ang_vel = new float[(int) 3];
        System.arraycopy(this.ang_vel, 0, outobj.ang_vel, 0, 3); 
        return outobj;
    }
 
}

