"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class odometry_msg(object):
    __slots__ = ["position", "orientation", "orientation_quaternion", "lin_vel", "ang_vel"]

    __typenames__ = ["float", "float", "float", "float", "float"]

    __dimensions__ = [[3], [3], [4], [3], [3]]

    def __init__(self):
        self.position = [ 0.0 for dim0 in range(3) ]
        self.orientation = [ 0.0 for dim0 in range(3) ]
        self.orientation_quaternion = [ 0.0 for dim0 in range(4) ]
        self.lin_vel = [ 0.0 for dim0 in range(3) ]
        self.ang_vel = [ 0.0 for dim0 in range(3) ]

    def encode(self):
        buf = BytesIO()
        buf.write(odometry_msg._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>3f', *self.position[:3]))
        buf.write(struct.pack('>3f', *self.orientation[:3]))
        buf.write(struct.pack('>4f', *self.orientation_quaternion[:4]))
        buf.write(struct.pack('>3f', *self.lin_vel[:3]))
        buf.write(struct.pack('>3f', *self.ang_vel[:3]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != odometry_msg._get_packed_fingerprint():
            raise ValueError("Decode error")
        return odometry_msg._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = odometry_msg()
        self.position = struct.unpack('>3f', buf.read(12))
        self.orientation = struct.unpack('>3f', buf.read(12))
        self.orientation_quaternion = struct.unpack('>4f', buf.read(16))
        self.lin_vel = struct.unpack('>3f', buf.read(12))
        self.ang_vel = struct.unpack('>3f', buf.read(12))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if odometry_msg in parents: return 0
        tmphash = (0xe6bb50a46c73bed8) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if odometry_msg._packed_fingerprint is None:
            odometry_msg._packed_fingerprint = struct.pack(">Q", odometry_msg._get_hash_recursive([]))
        return odometry_msg._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", odometry_msg._get_packed_fingerprint())[0]

