/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package mors_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class phase_signal_msg implements lcm.lcm.LCMEncodable
{
    public float t;
    public short phase[];
    public float phi[];
 
    public phase_signal_msg()
    {
        phase = new short[4];
        phi = new float[4];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x8c02eaa7c1bd8cd5L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(mors_msgs.phase_signal_msg.class))
            return 0L;
 
        classes.add(mors_msgs.phase_signal_msg.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeFloat(this.t); 
 
        for (int a = 0; a < 4; a++) {
            outs.writeShort(this.phase[a]); 
        }
 
        for (int a = 0; a < 4; a++) {
            outs.writeFloat(this.phi[a]); 
        }
 
    }
 
    public phase_signal_msg(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public phase_signal_msg(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static mors_msgs.phase_signal_msg _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        mors_msgs.phase_signal_msg o = new mors_msgs.phase_signal_msg();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.t = ins.readFloat();
 
        this.phase = new short[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.phase[a] = ins.readShort();
        }
 
        this.phi = new float[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.phi[a] = ins.readFloat();
        }
 
    }
 
    public mors_msgs.phase_signal_msg copy()
    {
        mors_msgs.phase_signal_msg outobj = new mors_msgs.phase_signal_msg();
        outobj.t = this.t;
 
        outobj.phase = new short[(int) 4];
        System.arraycopy(this.phase, 0, outobj.phase, 0, 4); 
        outobj.phi = new float[(int) 4];
        System.arraycopy(this.phi, 0, outobj.phi, 0, 4); 
        return outobj;
    }
 
}

