"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class phase_signal_msg(object):
    __slots__ = ["t", "phase", "phi"]

    __typenames__ = ["float", "int16_t", "float"]

    __dimensions__ = [None, [4], [4]]

    def __init__(self):
        self.t = 0.0
        self.phase = [ 0 for dim0 in range(4) ]
        self.phi = [ 0.0 for dim0 in range(4) ]

    def encode(self):
        buf = BytesIO()
        buf.write(phase_signal_msg._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">f", self.t))
        buf.write(struct.pack('>4h', *self.phase[:4]))
        buf.write(struct.pack('>4f', *self.phi[:4]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != phase_signal_msg._get_packed_fingerprint():
            raise ValueError("Decode error")
        return phase_signal_msg._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = phase_signal_msg()
        self.t = struct.unpack(">f", buf.read(4))[0]
        self.phase = struct.unpack('>4h', buf.read(8))
        self.phi = struct.unpack('>4f', buf.read(16))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if phase_signal_msg in parents: return 0
        tmphash = (0x8c02eaa7c1bd8cd5) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if phase_signal_msg._packed_fingerprint is None:
            phase_signal_msg._packed_fingerprint = struct.pack(">Q", phase_signal_msg._get_hash_recursive([]))
        return phase_signal_msg._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", phase_signal_msg._get_packed_fingerprint())[0]

