"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import mors_msgs.Body

import mors_msgs.Legs

class robot_state_msg(object):
    __slots__ = ["body", "legs"]

    __typenames__ = ["mors_msgs.Body", "mors_msgs.Legs"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.body = mors_msgs.Body()
        self.legs = mors_msgs.Legs()

    def encode(self):
        buf = BytesIO()
        buf.write(robot_state_msg._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.body._get_packed_fingerprint() == mors_msgs.Body._get_packed_fingerprint()
        self.body._encode_one(buf)
        assert self.legs._get_packed_fingerprint() == mors_msgs.Legs._get_packed_fingerprint()
        self.legs._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != robot_state_msg._get_packed_fingerprint():
            raise ValueError("Decode error")
        return robot_state_msg._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = robot_state_msg()
        self.body = mors_msgs.Body._decode_one(buf)
        self.legs = mors_msgs.Legs._decode_one(buf)
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if robot_state_msg in parents: return 0
        newparents = parents + [robot_state_msg]
        tmphash = (0x9d68b15c6e2c51c9+ mors_msgs.Body._get_hash_recursive(newparents)+ mors_msgs.Legs._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if robot_state_msg._packed_fingerprint is None:
            robot_state_msg._packed_fingerprint = struct.pack(">Q", robot_state_msg._get_hash_recursive([]))
        return robot_state_msg._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", robot_state_msg._get_packed_fingerprint())[0]

