"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class robot_cmd_msg(object):
    __slots__ = ["active_legs", "adaptation_type", "cmd_vel", "cmd_pose"]

    __typenames__ = ["boolean", "int8_t", "float", "float"]

    __dimensions__ = [[4], None, [6], [6]]

    def __init__(self):
        self.active_legs = [ False for dim0 in range(4) ]
        self.adaptation_type = 0
        self.cmd_vel = [ 0.0 for dim0 in range(6) ]
        self.cmd_pose = [ 0.0 for dim0 in range(6) ]

    def encode(self):
        buf = BytesIO()
        buf.write(robot_cmd_msg._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>4b', *self.active_legs[:4]))
        buf.write(struct.pack(">b", self.adaptation_type))
        buf.write(struct.pack('>6f', *self.cmd_vel[:6]))
        buf.write(struct.pack('>6f', *self.cmd_pose[:6]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != robot_cmd_msg._get_packed_fingerprint():
            raise ValueError("Decode error")
        return robot_cmd_msg._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = robot_cmd_msg()
        self.active_legs = [bool(x) for x in struct.unpack('>4b', buf.read(4))]
        self.adaptation_type = struct.unpack(">b", buf.read(1))[0]
        self.cmd_vel = struct.unpack('>6f', buf.read(24))
        self.cmd_pose = struct.unpack('>6f', buf.read(24))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if robot_cmd_msg in parents: return 0
        tmphash = (0x6e7c66b8f5fa9fc5) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if robot_cmd_msg._packed_fingerprint is None:
            robot_cmd_msg._packed_fingerprint = struct.pack(">Q", robot_cmd_msg._get_hash_recursive([]))
        return robot_cmd_msg._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", robot_cmd_msg._get_packed_fingerprint())[0]

