/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package mors_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class robot_cmd_msg implements lcm.lcm.LCMEncodable
{
    public boolean active_legs[];
    public byte adaptation_type;
    public float cmd_vel[];
    public float cmd_pose[];
 
    public robot_cmd_msg()
    {
        active_legs = new boolean[4];
        cmd_vel = new float[6];
        cmd_pose = new float[6];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x6e7c66b8f5fa9fc5L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(mors_msgs.robot_cmd_msg.class))
            return 0L;
 
        classes.add(mors_msgs.robot_cmd_msg.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        for (int a = 0; a < 4; a++) {
            outs.writeByte( this.active_legs[a] ? 1 : 0); 
        }
 
        outs.writeByte(this.adaptation_type); 
 
        for (int a = 0; a < 6; a++) {
            outs.writeFloat(this.cmd_vel[a]); 
        }
 
        for (int a = 0; a < 6; a++) {
            outs.writeFloat(this.cmd_pose[a]); 
        }
 
    }
 
    public robot_cmd_msg(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public robot_cmd_msg(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static mors_msgs.robot_cmd_msg _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        mors_msgs.robot_cmd_msg o = new mors_msgs.robot_cmd_msg();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.active_legs = new boolean[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.active_legs[a] = ins.readByte()!=0;
        }
 
        this.adaptation_type = ins.readByte();
 
        this.cmd_vel = new float[(int) 6];
        for (int a = 0; a < 6; a++) {
            this.cmd_vel[a] = ins.readFloat();
        }
 
        this.cmd_pose = new float[(int) 6];
        for (int a = 0; a < 6; a++) {
            this.cmd_pose[a] = ins.readFloat();
        }
 
    }
 
    public mors_msgs.robot_cmd_msg copy()
    {
        mors_msgs.robot_cmd_msg outobj = new mors_msgs.robot_cmd_msg();
        outobj.active_legs = new boolean[(int) 4];
        System.arraycopy(this.active_legs, 0, outobj.active_legs, 0, 4); 
        outobj.adaptation_type = this.adaptation_type;
 
        outobj.cmd_vel = new float[(int) 6];
        System.arraycopy(this.cmd_vel, 0, outobj.cmd_vel, 0, 6); 
        outobj.cmd_pose = new float[(int) 6];
        System.arraycopy(this.cmd_pose, 0, outobj.cmd_pose, 0, 6); 
        return outobj;
    }
 
}

