/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package mors_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class servo_cmd_msg implements lcm.lcm.LCMEncodable
{
    public float timestamp;
    public float position[];
    public float velocity[];
    public float torque[];
    public float kp[];
    public float kd[];
 
    public servo_cmd_msg()
    {
        position = new float[12];
        velocity = new float[12];
        torque = new float[12];
        kp = new float[12];
        kd = new float[12];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xaccd131c2302bee2L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(mors_msgs.servo_cmd_msg.class))
            return 0L;
 
        classes.add(mors_msgs.servo_cmd_msg.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeFloat(this.timestamp); 
 
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.position[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.velocity[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.torque[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.kp[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.kd[a]); 
        }
 
    }
 
    public servo_cmd_msg(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public servo_cmd_msg(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static mors_msgs.servo_cmd_msg _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        mors_msgs.servo_cmd_msg o = new mors_msgs.servo_cmd_msg();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.timestamp = ins.readFloat();
 
        this.position = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.position[a] = ins.readFloat();
        }
 
        this.velocity = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.velocity[a] = ins.readFloat();
        }
 
        this.torque = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.torque[a] = ins.readFloat();
        }
 
        this.kp = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.kp[a] = ins.readFloat();
        }
 
        this.kd = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.kd[a] = ins.readFloat();
        }
 
    }
 
    public mors_msgs.servo_cmd_msg copy()
    {
        mors_msgs.servo_cmd_msg outobj = new mors_msgs.servo_cmd_msg();
        outobj.timestamp = this.timestamp;
 
        outobj.position = new float[(int) 12];
        System.arraycopy(this.position, 0, outobj.position, 0, 12); 
        outobj.velocity = new float[(int) 12];
        System.arraycopy(this.velocity, 0, outobj.velocity, 0, 12); 
        outobj.torque = new float[(int) 12];
        System.arraycopy(this.torque, 0, outobj.torque, 0, 12); 
        outobj.kp = new float[(int) 12];
        System.arraycopy(this.kp, 0, outobj.kp, 0, 12); 
        outobj.kd = new float[(int) 12];
        System.arraycopy(this.kd, 0, outobj.kd, 0, 12); 
        return outobj;
    }
 
}

