"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class std_int(object):
    __slots__ = ["data"]

    __typenames__ = ["int32_t"]

    __dimensions__ = [None]

    def __init__(self):
        self.data = 0

    def encode(self):
        buf = BytesIO()
        buf.write(std_int._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.data))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != std_int._get_packed_fingerprint():
            raise ValueError("Decode error")
        return std_int._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = std_int()
        self.data = struct.unpack(">i", buf.read(4))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if std_int in parents: return 0
        tmphash = (0x165e7cfbf548811f) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if std_int._packed_fingerprint is None:
            std_int._packed_fingerprint = struct.pack(">Q", std_int._get_hash_recursive([]))
        return std_int._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", std_int._get_packed_fingerprint())[0]

