/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package mors_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class std_int implements lcm.lcm.LCMEncodable
{
    public int data;
 
    public std_int()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x165e7cfbf548811fL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(mors_msgs.std_int.class))
            return 0L;
 
        classes.add(mors_msgs.std_int.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeInt(this.data); 
 
    }
 
    public std_int(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public std_int(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static mors_msgs.std_int _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        mors_msgs.std_int o = new mors_msgs.std_int();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.data = ins.readInt();
 
    }
 
    public mors_msgs.std_int copy()
    {
        mors_msgs.std_int outobj = new mors_msgs.std_int();
        outobj.data = this.data;
 
        return outobj;
    }
 
}

