/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package mors_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class wbc_msg implements lcm.lcm.LCMEncodable
{
    public mors_msgs.Body body;
    public mors_msgs.Legs legs;
 
    public wbc_msg()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x9d68b15c6e2c51c9L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(mors_msgs.wbc_msg.class))
            return 0L;
 
        classes.add(mors_msgs.wbc_msg.class);
        long hash = LCM_FINGERPRINT_BASE
             + mors_msgs.Body._hashRecursive(classes)
             + mors_msgs.Legs._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        this.body._encodeRecursive(outs); 
 
        this.legs._encodeRecursive(outs); 
 
    }
 
    public wbc_msg(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public wbc_msg(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static mors_msgs.wbc_msg _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        mors_msgs.wbc_msg o = new mors_msgs.wbc_msg();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.body = mors_msgs.Body._decodeRecursiveFactory(ins);
 
        this.legs = mors_msgs.Legs._decodeRecursiveFactory(ins);
 
    }
 
    public mors_msgs.wbc_msg copy()
    {
        mors_msgs.wbc_msg outobj = new mors_msgs.wbc_msg();
        outobj.body = this.body.copy();
 
        outobj.legs = this.legs.copy();
 
        return outobj;
    }
 
}

