max_angles: [1.3, 2.6, 54.0, 
             1.3, 2.6,  54.0,
             1.3, 2.6, 54.0,
             1.3, 2.6,  54.0]

min_angles: [-1.3, -2.6,  -54.0,
             -1.3, -2.6, -54.0,
             -1.3, -2.6,  -54.0,
             -1.3, -2.6, -54.0]
