max_angles: [1.2, 2.7, 54.0, 
             1.2, 2.7,  54.0,
             1.2, 2.7, 54.0,
             1.2, 2.7,  54.0]

min_angles: [-1.2, -2.7,  -54.0,
             -1.2, -2.7, -54.0,
             -1.2, -2.7,  -54.0,
             -1.2, -2.7, -54.0]
