
# HARDWARE
# # swing trajectory generator
# interleave_x: [0.0, 0.0, 0.0, 0.0]
# interleave_y: [0.08, 0.08, 0.08, 0.08]
# dz_near_ground: -0.1

# # foot step planner
# k1_fsp: 0.02 #0.03 # capture point constant
# k2_fsp: 0.14 #0.0 # centrifugal term constant

# SIMULATION
# swing trajectory generator
interleave_x: [0.0, 0.0, 0.0, 0.0]
interleave_y: [0.1, 0.1, 0.1, 0.1]
dz_near_ground: -0.1

# foot step planner
k1_fsp: 0.02 #0.03 # capture point constant
k2_fsp: 0.14 #0.0 # centrifugal term constant
