#!/usr/bin/env python3
"""Generate an MJCF scene with a single rectangular platform."""

from __future__ import annotations

import argparse
from pathlib import Path


PLATFORM_START_X = 1.0
DEFAULT_OUTPUT = Path(__file__).with_name("platform.xml")


def positive_float(value: str) -> float:
    parsed = float(value)
    if parsed <= 0:
        raise argparse.ArgumentTypeError("value must be greater than zero")
    return parsed


def fmt(value: float) -> str:
    text = f"{value:.6f}".rstrip("0").rstrip(".")
    return text if text and text != "-0" else "0"


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Generate an MJCF scene with a single rectangular platform. "
            f"By default the platform starts at x = {fmt(PLATFORM_START_X)} m."
        )
    )
    parser.add_argument(
        "--height",
        required=True,
        type=positive_float,
        help="Platform height in meters.",
    )
    parser.add_argument(
        "--length",
        required=True,
        type=positive_float,
        help="Platform length along X in meters.",
    )
    parser.add_argument(
        "--width",
        required=True,
        type=positive_float,
        help="Platform width along Y in meters.",
    )
    position = parser.add_mutually_exclusive_group()
    position.add_argument(
        "--start-dist",
        type=float,
        help=(
            "X coordinate of the platform's near edge in meters "
            f"(default: {fmt(PLATFORM_START_X)})."
        ),
    )
    position.add_argument(
        "--center-pos",
        "--center-x",
        dest="center_pos",
        type=float,
        help="X coordinate of the platform center in meters.",
    )
    return parser


def resolve_center_x(args: argparse.Namespace) -> float:
    if args.center_pos is not None:
        return args.center_pos
    start_x = args.start_dist if args.start_dist is not None else PLATFORM_START_X
    return start_x + args.length / 2.0


def make_platform_geom(height: float, length: float, width: float, center_x: float) -> str:
    half_height = height / 2.0
    return "\n".join(
        [
            "    <geom",
            '      name="platform"',
            '      type="box"',
            f'      pos="{fmt(center_x)} 0 {fmt(half_height)}"',
            f'      size="{fmt(length / 2.0)} {fmt(width / 2.0)} {fmt(half_height)}"',
            '      contype="1"',
            '      conaffinity="1"',
            '      material="platform_geom"',
            "    />",
        ]
    )


def render_scene(height: float, length: float, width: float, center_x: float) -> str:
    platform_geom = make_platform_geom(height, length, width, center_x)

    ground_half_x = max(15.0, abs(center_x) + length / 2.0 + 2.0)
    ground_half_y = max(15.0, width / 2.0 + 2.0)
    statistic_center_z = max(0.1, height)
    statistic_extent = 2

    return f"""<mujoco model="{{name}} platform scene">
  <include file="{{path}}" />

  <statistic center="{fmt(center_x)} 0 {fmt(statistic_center_z)}" extent="{fmt(statistic_extent)}" meansize="0.04" />

  <visual>
    <headlight diffuse="0.0 0.0 0.0" ambient="0.0 0.0 0.0" specular="0.0 0.0 0.0" />
    <global azimuth="220" elevation="-10" />
    <quality shadowsize="8192" />
  </visual>

  <asset>
    <texture name="grid" type="2d" builtin="checker" rgb1=".1 .2 .3"
     rgb2=".2 .3 .4" width="300" height="300" mark="edge" markrgb=".2 .3 .4"/>
    <material name="grid" texture="grid" texrepeat="15 15" reflectance=".05"/>
  </asset>

  <asset>
    <texture
      type="skybox"
      builtin="gradient"
      rgb1="0.2 0.2 0.9"
      rgb2="0.1 0.6 0.2"
      width="512"
      height="3072"
    />
    <material name="platform_geom" rgba="0.70 0.45 0.20 1" />
  </asset>

  <worldbody>
    <light
      name="sun"
      directional="true"
      dir="-0.5 -0.4 -1"
      diffuse="0.4 0.4 0.4"
      specular="0.2 0.2 0.2"
      ambient="0.01 0.01 0.01"
      castshadow="true"
    />

    <light
      name="spotlight1"
      mode="targetbodycom"
      target="base"
      diffuse="0.2 0.2 0.2"
      specular="0.1 0.1 0.1"
      pos="0 -10 4"
      cutoff="10"
    />

    <light
      name="spotlight2"
      mode="targetbodycom"
      directional="true"
      target="base"
      diffuse="0.2 0.2 0.2"
      specular="0.1 0.1 0.1"
      pos="10 0 4"
      dir="1 0 0"
      cutoff="10"
      castshadow="false"
    />

    <geom name="ground" type="plane" pos="0 0 0" size="{fmt(ground_half_x)} {fmt(ground_half_y)} 0.1" material="grid"/>

{platform_geom}
  </worldbody>
</mujoco>
"""


def render_generation_comment(height: float, length: float, width: float, center_x: float) -> str:
    return "\n".join(
        [
            "<!-- Generated by generate_platform.py with arguments:",
            f"  height {fmt(height)}",
            f"  length {fmt(length)}",
            f"  width {fmt(width)}",
            f"  start-dist {fmt(center_x - length / 2.0)}",
            f"  center-pos {fmt(center_x)}",
            "-->",
        ]
    )


def main() -> None:
    args = build_parser().parse_args()
    params = dict(
        height=args.height,
        length=args.length,
        width=args.width,
        center_x=resolve_center_x(args),
    )
    xml = f"{render_generation_comment(**params)}\n{render_scene(**params)}"

    DEFAULT_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    DEFAULT_OUTPUT.write_text(xml, encoding="utf-8")
    print(f"Generated {DEFAULT_OUTPUT}")


if __name__ == "__main__":
    main()
